name: devclub360
description: A project to connect real estate developers of high worth.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_pro_nullsafety: ^1.0.2
  password_strength: ^0.2.0
  connectivity_plus: ^1.0.5
  provider: ^5.0.0
  internet_connection_checker: ^0.0.1+1
  overlay_support: ^1.2.1
  firebase_auth: ^3.1.1
  flutter_signin_button: ^2.0.0
  http: ^0.13.3
  cloud_firestore: ^2.5.3
  firebase_core: ^1.6.0
  fluttertoast: ^8.0.7
  google_sign_in: ^5.0.5
  flutter_paystack: ^1.0.5+1
  google_nav_bar: ^5.0.5
  image_picker: ^0.8.3+2
  flutter_multiselect: ^1.0.0
  cloudinary_public: ^0.9.0
  badges: ^2.0.1
  google_fonts: ^2.1.0
  multi_image_picker2: ^5.0.02
  group_radio_button: ^1.1.0
  syncfusion_flutter_pdfviewer: ^19.2.57-beta
  awesome_notifications: ^0.0.6+10
  flutter_launcher_icons: ^0.9.2
  font_awesome_flutter: ^9.1.0
  percent_indicator: ^3.0.1
  url_launcher: ^6.0.12
  firebase_messaging: ^10.0.7
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/devclub_icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/files/
    - assets/icons/
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #fonts:
     # - family: Lobster
      #  fonts:
        #  - asset: assets/fonts/Lobster-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
